import Navbar from '@/components/Navbar'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const navbarHeight = 85
const style = {
  minHeight: `calc(100vh - ${navbarHeight}px)`,
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className='bg-gray-600' style={style}>
        {children}
      </body>
      <Navbar />
    </html>
  )
}
